// Compatibility entrypoint: feature modules should prefer importing their
// domain API directly, while existing callers can keep using "@/api/client".
export type { AssetCategoryDefinition, AssetTypeDefinition } from '@/types'
export { OpsApiError } from './http'
export * from './alerts'
export * from './approvals'
export * from './assets'
export * from './config'
export * from './cron'
export * from './dashboard'
export * from './hydrate'
export * from './knowledge'
export * from './notifications'
export * from './safety'
export * from './sessions'
export * from './skills'
export * from './tools'
