"""Built-in read-only inspection template catalog."""

from __future__ import annotations

from typing import Any


ALLOWED_TOOLS = {
    "linux_execute_command",
    "container_execute_command",
    "middleware_execute_command",
    "storage_execute_command",
    "network_cli_execute_command",
    "winrm_execute_command",
    "db_execute_query",
    "redis_execute_command",
    "memcached_execute_command",
    "mongodb_find",
    "http_api_request",
    "database_api_request",
    "bigdata_api_request",
    "middleware_api_request",
    "discovery_api_request",
    "container_api_request",
    "network_api_request",
    "security_api_request",
    "cicd_api_request",
    "ai_platform_api_request",
    "oob_api_request",
    "k8s_api_request",
    "monitoring_api_query",
    "virtualization_api_request",
    "storage_api_request",
    "service_probe_request",
    "snmp_get",
}

WINDOWS_SECURITY_AUDIT_COMMAND = (
    "$start=(Get-Date).AddDays(-1); "
    "$Error.Clear(); "
    "try { "
    "$events=Get-WinEvent -FilterHashtable @{LogName='Security'; Id=4625,4624,4648,4672,4720,4726,4732,4733; StartTime=$start} -MaxEvents 30 -ErrorAction SilentlyContinue | "
    "Select-Object TimeCreated,Id,ProviderName,LevelDisplayName,Message; "
    "if ($Error.Count -gt 0 -and @($events).Count -eq 0) { "
    "$err=$Error[0].Exception.Message; "
    "try { $groups=whoami /groups } catch { $groups=@() }; "
    "try { $identity=whoami } catch { $identity='' }; "
    "[pscustomobject]@{status='permission_denied'; log='Security'; message='当前 WinRM 账号无法读取 Windows Security 事件日志。请将该账号加入本机 Administrators 或 Event Log Readers；若使用本地账号远程访问，还需要确认 WinRM/UAC 远程令牌策略。'; error=$err; identity=$identity; groups=$groups; fallback='已保留 System/Application 日志巡检结果；Security 登录成功/失败、特权登录和账号调整事件需要提升读取权限后才能获取。'} | ConvertTo-Json -Compress -Depth 4 "
    "} else { "
    "[pscustomobject]@{status='ok'; log='Security'; event_count=@($events).Count; events=$events} | ConvertTo-Json -Compress -Depth 4 "
    "} "
    "} catch { "
    "try { $groups=whoami /groups } catch { $groups=@() }; "
    "try { $identity=whoami } catch { $identity='' }; "
    "[pscustomobject]@{status='permission_denied'; log='Security'; message='当前 WinRM 账号无法读取 Windows Security 事件日志。请将该账号加入本机 Administrators 或 Event Log Readers；若使用本地账号远程访问，还需要确认 WinRM/UAC 远程令牌策略。'; error=$_.Exception.Message; identity=$identity; groups=$groups; fallback='已保留 System/Application 日志巡检结果；Security 登录成功/失败、特权登录和账号调整事件需要提升读取权限后才能获取。'} | ConvertTo-Json -Compress -Depth 4 "
    "}"
)


def _db_step(name: str, title: str, sql: str, timeout: int = 30) -> dict[str, Any]:
    return {
        "name": name,
        "title": title,
        "tool": "db_execute_query",
        "sql": sql,
        "timeout": timeout,
    }


BUILTIN_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "builtin-k8s-core-readonly",
        "name": "Kubernetes 核心只读巡检",
        "asset_type": "k8s",
        "protocol": "k8s",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "nodes",
                "title": "节点列表",
                "tool": "k8s_api_request",
                "method": "GET",
                "path": "/api/v1/nodes",
                "timeout": 20,
            },
            {
                "name": "pods",
                "title": "Pod 列表",
                "tool": "k8s_api_request",
                "method": "GET",
                "path": "/api/v1/pods",
                "timeout": 20,
            },
            {
                "name": "deployments",
                "title": "Deployment 列表",
                "tool": "k8s_api_request",
                "method": "GET",
                "path": "/apis/apps/v1/deployments",
                "timeout": 20,
            },
            {
                "name": "events",
                "title": "事件列表",
                "tool": "k8s_api_request",
                "method": "GET",
                "path": "/api/v1/events",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-prometheus-core-readonly",
        "name": "Prometheus 核心只读巡检",
        "asset_type": "prometheus",
        "protocol": "http_api",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "build_info",
                "title": "版本信息",
                "tool": "monitoring_api_query",
                "method": "GET",
                "path": "/api/v1/status/buildinfo",
                "timeout": 15,
            },
            {
                "name": "targets",
                "title": "采集目标状态",
                "tool": "monitoring_api_query",
                "method": "GET",
                "path": "/api/v1/targets",
                "timeout": 20,
            },
            {
                "name": "up",
                "title": "Up 指标",
                "tool": "monitoring_api_query",
                "method": "GET",
                "path": "/api/v1/query?query=up",
                "timeout": 20,
            },
            {
                "name": "alerts",
                "title": "当前告警",
                "tool": "monitoring_api_query",
                "method": "GET",
                "path": "/api/v1/query?query=ALERTS",
                "timeout": 20,
            },
            {
                "name": "cpu_usage",
                "title": "CPU 使用率",
                "tool": "monitoring_api_query",
                "method": "GET",
                "path": "/api/v1/query?query=100%20-%20(avg%20by(instance)%20(rate(node_cpu_seconds_total%7Bmode%3D%22idle%22%7D%5B5m%5D))%20*%20100)",
                "timeout": 20,
            },
            {
                "name": "memory_usage",
                "title": "内存使用率",
                "tool": "monitoring_api_query",
                "method": "GET",
                "path": "/api/v1/query?query=(1%20-%20(node_memory_MemAvailable_bytes%20/%20node_memory_MemTotal_bytes))%20*%20100",
                "timeout": 20,
            },
            {
                "name": "disk_usage",
                "title": "磁盘使用率",
                "tool": "monitoring_api_query",
                "method": "GET",
                "path": "/api/v1/query?query=100%20-%20(node_filesystem_avail_bytes%7Bfstype!~%22tmpfs%7Coverlay%22%7D%20*%20100%20/%20node_filesystem_size_bytes%7Bfstype!~%22tmpfs%7Coverlay%22%7D)",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-windows-core-readonly",
        "name": "Windows 核心只读巡检",
        "asset_type": "windows",
        "protocol": "winrm",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "os",
                "title": "系统版本与启动时间",
                "tool": "winrm_execute_command",
                "command": "Get-CimInstance Win32_OperatingSystem | Select-Object Caption,Version,BuildNumber,LastBootUpTime,InstallDate | ConvertTo-Json -Compress",
                "timeout": 20,
            },
            {
                "name": "hardware",
                "title": "硬件资源",
                "tool": "winrm_execute_command",
                "command": "Get-CimInstance Win32_ComputerSystem | Select-Object Manufacturer,Model,TotalPhysicalMemory,NumberOfLogicalProcessors | ConvertTo-Json -Compress",
                "timeout": 20,
            },
            {
                "name": "disk",
                "title": "磁盘空间",
                "tool": "winrm_execute_command",
                "command": "Get-CimInstance Win32_LogicalDisk -Filter \"DriveType=3\" | Select-Object DeviceID,Size,FreeSpace | ConvertTo-Json -Compress",
                "timeout": 20,
            },
            {
                "name": "services",
                "title": "异常服务",
                "tool": "winrm_execute_command",
                "command": "Get-Service | Where-Object {$_.Status -ne 'Running'} | Select-Object -First 30 Name,Status,DisplayName | ConvertTo-Json -Compress",
                "timeout": 20,
            },
            {
                "name": "events",
                "title": "近 24 小时系统错误事件",
                "tool": "winrm_execute_command",
                "command": "Get-WinEvent -FilterHashtable @{LogName='System'; Level=1,2; StartTime=(Get-Date).AddDays(-1)} -MaxEvents 20 | Select-Object TimeCreated,Id,ProviderName,LevelDisplayName,Message | ConvertTo-Json -Compress",
                "timeout": 30,
            },
            {
                "name": "security_events",
                "title": "安全登录与账号事件",
                "tool": "winrm_execute_command",
                "command": WINDOWS_SECURITY_AUDIT_COMMAND,
                "timeout": 30,
            },
            {
                "name": "hotfixes",
                "title": "最近补丁",
                "tool": "winrm_execute_command",
                "command": "Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 10 HotFixID,InstalledOn,Description | ConvertTo-Json -Compress",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-hyperv-core-readonly",
        "name": "Hyper-V 核心只读巡检",
        "asset_type": "hyperv",
        "protocol": "winrm",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "host",
                "title": "宿主机信息",
                "tool": "winrm_execute_command",
                "command": "Get-VMHost | Select-Object ComputerName,LogicalProcessorCount,MemoryCapacity,VirtualHardDiskPath,VirtualMachinePath | ConvertTo-Json -Compress",
                "timeout": 20,
            },
            {
                "name": "vms",
                "title": "虚拟机列表",
                "tool": "winrm_execute_command",
                "command": "Get-VM | Select-Object Name,State,Status,CPUUsage,MemoryAssigned,Uptime,Generation,Version | ConvertTo-Json -Compress",
                "timeout": 30,
            },
            {
                "name": "switches",
                "title": "虚拟交换机",
                "tool": "winrm_execute_command",
                "command": "Get-VMSwitch | Select-Object Name,SwitchType,NetAdapterInterfaceDescription,AllowManagementOS | ConvertTo-Json -Compress",
                "timeout": 20,
            },
            {
                "name": "vm_network",
                "title": "虚拟机网络适配器",
                "tool": "winrm_execute_command",
                "command": "Get-VMNetworkAdapter -All | Select-Object VMName,Name,SwitchName,Status,MacAddress,IPAddresses | ConvertTo-Json -Compress",
                "timeout": 30,
            },
            {
                "name": "vm_disks",
                "title": "虚拟机磁盘",
                "tool": "winrm_execute_command",
                "command": "Get-VMHardDiskDrive -VMName * | Select-Object VMName,ControllerType,ControllerNumber,ControllerLocation,Path | ConvertTo-Json -Compress",
                "timeout": 30,
            },
            {
                "name": "replication",
                "title": "复制状态",
                "tool": "winrm_execute_command",
                "command": "Get-VMReplication | Select-Object VMName,State,Health,Mode,FrequencySec | ConvertTo-Json -Compress",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-tidb-core-readonly",
        "name": "TiDB 核心只读巡检",
        "asset_type": "tidb",
        "asset_types": ["tidb"],
        "protocol": "mysql",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            _db_step("version", "TiDB 版本", "SELECT TIDB_VERSION() AS version", 20),
            _db_step("connections", "当前连接数", "SHOW GLOBAL STATUS LIKE 'Threads_connected'", 20),
            _db_step("max_connections", "最大连接配置", "SHOW GLOBAL VARIABLES LIKE 'max_connections'", 20),
            _db_step("slow_queries", "慢查询计数", "SHOW GLOBAL STATUS LIKE 'Slow_queries'", 20),
            _db_step("cluster_info", "集群节点信息", "SELECT TYPE, INSTANCE, STATUS_ADDRESS, VERSION, GIT_HASH FROM information_schema.cluster_info ORDER BY TYPE, INSTANCE", 30),
            _db_step("tikv_store_status", "TiKV Store 状态", "SELECT STORE_ID, ADDRESS, STORE_STATE_NAME, CAPACITY, AVAILABLE, REGION_COUNT, LEADER_COUNT FROM information_schema.tikv_store_status ORDER BY STORE_ID", 30),
            _db_step("processlist", "当前会话列表", "SHOW FULL PROCESSLIST", 30),
            _db_step("schema_size", "库空间 TopN", "SELECT table_schema, ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS size_mb FROM information_schema.tables GROUP BY table_schema ORDER BY size_mb DESC LIMIT 20", 30),
        ],
    },
    {
        "id": "builtin-mysql-core-readonly",
        "name": "MySQL 协议核心只读巡检",
        "asset_type": "*",
        "protocol": "mysql",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "数据库版本",
                "tool": "db_execute_query",
                "sql": "SELECT VERSION() AS version",
                "timeout": 20,
            },
            {
                "name": "connections",
                "title": "当前连接数",
                "tool": "db_execute_query",
                "sql": "SHOW GLOBAL STATUS LIKE 'Threads_connected'",
                "timeout": 20,
            },
            {
                "name": "slow_queries",
                "title": "慢查询计数",
                "tool": "db_execute_query",
                "sql": "SHOW GLOBAL STATUS LIKE 'Slow_queries'",
                "timeout": 20,
            },
            {
                "name": "innodb_status",
                "title": "InnoDB 状态",
                "tool": "db_execute_query",
                "sql": "SHOW ENGINE INNODB STATUS",
                "timeout": 30,
            },
            {
                "name": "schema_size",
                "title": "库空间 TopN",
                "tool": "db_execute_query",
                "sql": "SELECT table_schema, ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS size_mb FROM information_schema.tables GROUP BY table_schema ORDER BY size_mb DESC LIMIT 20",
                "timeout": 30,
            },
            _db_step("uptime", "实例启动时间", "SELECT DATE_FORMAT(DATE_SUB(NOW(), INTERVAL VARIABLE_VALUE SECOND), '%Y-%m-%d %H:%i:%s') AS started_at FROM performance_schema.global_status WHERE VARIABLE_NAME='Uptime'", 20),
            _db_step("max_connections", "最大连接配置", "SHOW GLOBAL VARIABLES LIKE 'max_connections'", 20),
            _db_step("max_used_connections", "历史最大连接数", "SHOW GLOBAL STATUS LIKE 'Max_used_connections'", 20),
            _db_step("aborted_connections", "异常连接统计", "SHOW GLOBAL STATUS LIKE 'Aborted%'", 20),
            _db_step("key_parameters", "关键参数", "SHOW GLOBAL VARIABLES WHERE Variable_name IN ('back_log','max_allowed_packet','interactive_timeout','skip_name_resolve','open_files_limit','thread_cache_size','sort_buffer_size','join_buffer_size','innodb_buffer_pool_size','innodb_io_capacity','table_open_cache','innodb_file_per_table','innodb_flush_log_at_trx_commit','sync_binlog','innodb_log_file_size','slow_query_log','log_bin')", 30),
            _db_step("table_locks", "表锁等待统计", "SHOW GLOBAL STATUS WHERE Variable_name IN ('Table_locks_immediate','Table_locks_waited')", 20),
            _db_step("processlist", "当前会话列表", "SHOW FULL PROCESSLIST", 30),
            _db_step("replication_status", "复制状态", "SHOW SLAVE STATUS", 30),
            _db_step("mysql_users", "用户与认证插件", "SELECT user, host, plugin, account_locked FROM mysql.user WHERE user NOT IN ('mysql.infoschema','mysql.session','mysql.sys') ORDER BY user, host", 30),
        ],
    },
    {
        "id": "builtin-postgresql-core-readonly",
        "name": "PostgreSQL 协议核心只读巡检",
        "asset_type": "*",
        "protocol": "postgresql",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "数据库版本",
                "tool": "db_execute_query",
                "sql": "SELECT version() AS version",
                "timeout": 20,
            },
            {
                "name": "connections",
                "title": "连接概览",
                "tool": "db_execute_query",
                "sql": "SELECT state, count(*) AS sessions FROM pg_stat_activity GROUP BY state ORDER BY sessions DESC",
                "timeout": 20,
            },
            {
                "name": "database_stats",
                "title": "数据库统计",
                "tool": "db_execute_query",
                "sql": "SELECT datname, numbackends, xact_commit, xact_rollback, deadlocks FROM pg_stat_database ORDER BY deadlocks DESC LIMIT 20",
                "timeout": 20,
            },
            {
                "name": "active_queries",
                "title": "活跃查询",
                "tool": "db_execute_query",
                "sql": "SELECT pid, state, wait_event_type, wait_event, query FROM pg_stat_activity WHERE state <> 'idle' LIMIT 20",
                "timeout": 20,
            },
            {
                "name": "database_size",
                "title": "库空间 TopN",
                "tool": "db_execute_query",
                "sql": "SELECT datname, pg_size_pretty(pg_database_size(datname)) AS size FROM pg_database ORDER BY pg_database_size(datname) DESC LIMIT 20",
                "timeout": 30,
            },
            _db_step("uptime", "实例启动时间", "SELECT now() - pg_postmaster_start_time() AS uptime, pg_postmaster_start_time() AS start_time", 20),
            _db_step("wait_events", "等待事件 TopN", "SELECT wait_event_type, wait_event, count(*) AS count FROM pg_stat_activity WHERE wait_event IS NOT NULL GROUP BY wait_event_type, wait_event ORDER BY count DESC LIMIT 10", 20),
            _db_step("long_queries", "长时间查询", "SELECT pid, now()-query_start AS duration, state, left(query,120) AS query FROM pg_stat_activity WHERE state NOT IN ('idle') AND query_start IS NOT NULL AND now()-query_start > interval '30 seconds' ORDER BY duration DESC LIMIT 10", 20),
            _db_step("lock_info", "锁概览", "SELECT count(*) AS total_locks, sum(CASE WHEN granted THEN 1 ELSE 0 END) AS granted_locks, sum(CASE WHEN NOT granted THEN 1 ELSE 0 END) AS waiting_locks FROM pg_locks", 20),
            _db_step("table_stats", "表膨胀/统计 TopN", "SELECT schemaname, relname AS tablename, n_live_tup AS live_rows, n_dead_tup AS dead_rows, round(n_dead_tup*100.0/NULLIF(n_live_tup+n_dead_tup,0),2) AS dead_ratio, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 15", 30),
            _db_step("index_usage", "低扫描索引 TopN", "SELECT schemaname, relname AS tablename, indexrelname AS indexname, idx_scan, idx_tup_read, idx_tup_fetch FROM pg_stat_user_indexes ORDER BY idx_scan ASC LIMIT 15", 30),
            _db_step("replication", "复制状态", "SELECT pid, usename, application_name, client_addr, state, sent_lsn, write_lsn, flush_lsn, replay_lsn, sync_state FROM pg_stat_replication", 20),
            _db_step("cache_hit", "缓存命中率", "SELECT datname, blks_read, blks_hit, round(blks_hit*100.0/NULLIF(blks_hit+blks_read,0),2) AS cache_hit_ratio, tup_returned, tup_fetched, tup_inserted, tup_updated, tup_deleted FROM pg_stat_database WHERE datname NOT IN ('template0','template1') ORDER BY blks_hit DESC", 30),
            _db_step("settings_key", "关键参数", "SELECT name, setting, unit, short_desc FROM pg_settings WHERE name IN ('max_connections','shared_buffers','work_mem','maintenance_work_mem','effective_cache_size','wal_level','archive_mode','max_wal_size','checkpoint_completion_target','random_page_cost','log_min_duration_statement','autovacuum','autovacuum_vacuum_scale_factor','autovacuum_analyze_scale_factor') ORDER BY name", 30),
            _db_step("users", "用户与权限", "SELECT rolname AS username, rolsuper AS is_superuser, rolcreatedb AS can_createdb, rolcreaterole AS can_createrole, rolvaliduntil AS password_expiry FROM pg_roles ORDER BY rolname", 30),
        ],
    },
    {
        "id": "builtin-oracle-core-readonly",
        "name": "Oracle 核心只读巡检",
        "asset_type": "*",
        "protocol": "oracle",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "数据库版本",
                "tool": "db_execute_query",
                "sql": "SELECT banner FROM v$version",
                "timeout": 20,
            },
            {
                "name": "connections",
                "title": "会话数",
                "tool": "db_execute_query",
                "sql": "SELECT COUNT(*) AS sessions FROM v$session",
                "timeout": 20,
            },
            {
                "name": "tablespace_usage",
                "title": "表空间使用率",
                "tool": "db_execute_query",
                "sql": "SELECT tablespace_name, ROUND(used_percent, 2) AS used_percent FROM dba_tablespace_usage_metrics ORDER BY used_percent DESC",
                "timeout": 30,
            },
            {
                "name": "wait_events",
                "title": "等待事件 TopN",
                "tool": "db_execute_query",
                "sql": "SELECT event, total_waits, time_waited FROM v$system_event ORDER BY time_waited DESC",
                "timeout": 30,
            },
            _db_step("database_info", "数据库角色与模式", "SELECT name, database_role, log_mode, open_mode, force_logging, flashback_on FROM v$database", 20),
            _db_step("instance_info", "实例状态", "SELECT instance_name, host_name, version, startup_time, status, parallel, log_mode FROM v$instance", 20),
            _db_step("key_parameters", "关键参数", "SELECT name, value, display_value, isdefault FROM v$parameter WHERE name IN ('processes','sessions','open_cursors','db_block_size','sga_target','pga_aggregate_target','memory_target','undo_retention','compatible') ORDER BY name", 30),
            _db_step("session_status", "会话状态分布", "SELECT status, COUNT(*) AS sessions FROM v$session GROUP BY status", 20),
            _db_step("locked_users", "锁定/过期用户", "SELECT username, account_status, lock_date, expiry_date, created FROM dba_users WHERE account_status <> 'OPEN' ORDER BY username", 30),
            _db_step("invalid_objects", "无效对象 TopN", "SELECT owner, object_type, COUNT(*) AS cnt FROM dba_objects WHERE status='INVALID' GROUP BY owner, object_type ORDER BY cnt DESC", 30),
            _db_step("redolog", "Redo 日志", "SELECT group#, thread#, sequence#, ROUND(bytes/1024/1024,2) AS size_mb, status, members, archived FROM v$log ORDER BY group#", 20),
            _db_step("archive_dest", "归档目的地", "SELECT dest_id, status, destination, archiver, transmit_mode FROM v$archive_dest WHERE destination IS NOT NULL", 30),
            _db_step("rman_jobs", "近 30 天 RMAN 备份", "SELECT session_key, input_type, status, TO_CHAR(start_time,'YYYY-MM-DD HH24:MI') AS start_time, TO_CHAR(end_time,'YYYY-MM-DD HH24:MI') AS end_time, ROUND(input_bytes/1024/1024/1024,2) AS input_gb, elapsed_seconds FROM v$rman_backup_job_details WHERE end_time > SYSDATE - 30 ORDER BY start_time DESC", 45),
            _db_step("buffer_cache", "Buffer Cache 命中率", "SELECT name, ROUND((1 - physical_reads / (db_block_gets + consistent_gets)) * 100, 2) AS hit_pct, db_block_gets, consistent_gets, physical_reads FROM v$buffer_pool_statistics WHERE db_block_gets + consistent_gets > 0", 30),
        ],
    },
    {
        "id": "builtin-mssql-core-readonly",
        "name": "SQL Server 核心只读巡检",
        "asset_type": "*",
        "protocol": "mssql",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "数据库版本",
                "tool": "db_execute_query",
                "sql": "SELECT @@VERSION AS version",
                "timeout": 20,
            },
            {
                "name": "connections",
                "title": "会话数",
                "tool": "db_execute_query",
                "sql": "SELECT COUNT(*) AS sessions FROM sys.dm_exec_sessions",
                "timeout": 20,
            },
            {
                "name": "wait_stats",
                "title": "等待统计 TopN",
                "tool": "db_execute_query",
                "sql": "SELECT TOP 20 wait_type, wait_time_ms FROM sys.dm_os_wait_stats ORDER BY wait_time_ms DESC",
                "timeout": 30,
            },
            {
                "name": "database_files",
                "title": "数据库文件空间 TopN",
                "tool": "db_execute_query",
                "sql": "SELECT TOP 20 DB_NAME(database_id) AS database_name, name, size * 8 / 1024 AS size_mb FROM sys.master_files ORDER BY size DESC",
                "timeout": 30,
            },
            _db_step("server_properties", "实例属性", "SELECT @@VERSION AS full_version, SERVERPROPERTY('ProductVersion') AS product_version, SERVERPROPERTY('Edition') AS edition, SERVERPROPERTY('MachineName') AS machine_name", 20),
            _db_step("database_overview", "数据库状态与容量", "SELECT d.name AS database_name, d.state_desc, d.recovery_model_desc, d.compatibility_level, SUM(mf.size) * 8 / 1024 AS size_mb FROM sys.databases d LEFT JOIN sys.master_files mf ON d.database_id = mf.database_id GROUP BY d.name, d.state_desc, d.recovery_model_desc, d.compatibility_level ORDER BY size_mb DESC", 30),
            _db_step("active_sessions", "活跃会话 TopN", "SELECT TOP 50 s.session_id AS spid, s.login_name, s.host_name, s.program_name, s.status, s.cpu_time, s.memory_usage, r.wait_type, r.wait_time, r.blocking_session_id, SUBSTRING(t.text,1,500) AS sql_text FROM sys.dm_exec_sessions s LEFT JOIN sys.dm_exec_requests r ON s.session_id = r.session_id OUTER APPLY sys.dm_exec_sql_text(r.sql_handle) t WHERE s.session_id > 50 ORDER BY s.cpu_time DESC", 30),
            _db_step("blocking_sessions", "阻塞会话", "SELECT wait_session.session_id AS waiting_spid, wait_session.login_name AS waiting_login, wait_session.host_name AS waiting_host, wait_session.status AS waiting_status, req.wait_type, req.wait_time AS wait_time_ms, req.blocking_session_id, SUBSTRING(sql_text.text,1,500) AS waiting_sql FROM sys.dm_exec_sessions wait_session LEFT JOIN sys.dm_exec_requests req ON wait_session.session_id = req.session_id OUTER APPLY sys.dm_exec_sql_text(req.sql_handle) sql_text WHERE req.blocking_session_id > 0 ORDER BY req.wait_time DESC", 30),
            _db_step("locks", "锁统计", "SELECT DB_NAME(resource_database_id) AS database_name, resource_type, request_mode AS lock_mode, request_status AS lock_status, request_owner_type, COUNT(*) AS lock_count FROM sys.dm_tran_locks WHERE resource_database_id > 4 GROUP BY resource_database_id, resource_type, request_mode, request_status, request_owner_type ORDER BY lock_count DESC", 30),
            _db_step("io_stats", "数据文件 IO TopN", "SELECT TOP 20 DB_NAME(vf.database_id) AS database_name, mf.name, mf.physical_name, vf.num_of_reads, vf.num_of_writes, vf.io_stall_read_ms, vf.io_stall_write_ms FROM sys.dm_io_virtual_file_stats(NULL, NULL) vf INNER JOIN sys.master_files mf ON vf.database_id = mf.database_id AND vf.file_id = mf.file_id ORDER BY (vf.io_stall_read_ms + vf.io_stall_write_ms) DESC", 30),
            _db_step("backups", "近 30 天备份记录", "SELECT TOP 20 bs.database_name, bs.backup_start_date, bs.backup_finish_date, DATEDIFF(MINUTE, bs.backup_start_date, bs.backup_finish_date) AS duration_min, CAST(bs.backup_size / 1048576.0 AS DECIMAL(10,2)) AS backup_size_mb, bs.type AS backup_type, bs.user_name AS operator FROM msdb.dbo.backupset bs WHERE bs.backup_start_date > DATEADD(DAY, -30, GETDATE()) ORDER BY bs.backup_start_date DESC", 45),
        ],
    },
    {
        "id": "builtin-dameng-core-readonly",
        "name": "达梦 DM 核心只读巡检",
        "asset_type": "dameng",
        "asset_types": ["dameng", "dm"],
        "protocol": "dameng",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            _db_step("version", "实例版本", "SELECT INSTANCE_NAME, HOST_NAME, SVR_VERSION, DB_VERSION, START_TIME, STATUS$, MODE$ FROM V$INSTANCE", 20),
            _db_step("database", "数据库状态", "SELECT NAME, CREATE_TIME, ARCH_MODE, STATUS$, ROLE$, MAX_SIZE, TOTAL_SIZE FROM V$DATABASE", 20),
            _db_step("sessions", "会话列表 TopN", "SELECT TOP 50 SESS_ID, SESS_SEQ, USER_NAME, STATE, TRX_ID, CREATE_TIME, CLNT_IP FROM V$SESSIONS ORDER BY STATE, SESS_SEQ DESC", 30),
            _db_step("session_count", "活跃会话数", "SELECT COUNT(*) AS total_active FROM V$SESSIONS WHERE STATE='ACTIVE'", 20),
            _db_step("tablespace", "表空间与数据文件", "SELECT T.TABLESPACE_NAME, T.STATUS AS TS_STATUS, D.FILE_NAME, D.BYTES/1024/1024 AS FILE_SIZE_MB, D.STATUS AS FILE_STATUS, D.AUTOEXTENSIBLE, D.MAXBYTES/1024/1024 AS MAX_SIZE_MB FROM DBA_TABLESPACES T LEFT JOIN DBA_DATA_FILES D ON T.TABLESPACE_NAME=D.TABLESPACE_NAME ORDER BY T.TABLESPACE_NAME", 30),
            _db_step("memory", "Buffer Pool", "SELECT NAME, PAGE_SIZE, N_PAGES, N_FIXED FROM V$BUFFERPOOL ORDER BY NAME", 30),
            _db_step("redo_logs", "Redo 日志", "SELECT GROUP_ID, FILE_ID, PATH, CREATE_TIME FROM V$RLOGFILE ORDER BY GROUP_ID", 30),
            _db_step("archive_config", "归档配置", "SELECT NAME, VALUE FROM V$PARAMETER WHERE NAME IN ('ARCH_DIR', 'ARCH_FILE_SIZE', 'ARCH_MODE')", 20),
            _db_step("backup", "备份记录 TopN", "SELECT TOP 20 BACKUP_NAME, LEVEL, BACKUP_PATH, BACKUP_TIME, DEVICE_TYPE, OBJECT_NAME FROM V$BACKUPSET ORDER BY BACKUP_TIME DESC", 45),
            _db_step("locks", "锁等待", "SELECT TRX_ID, LTYPE, LMODE, BLOCKED FROM V$LOCK", 30),
            _db_step("wait_events", "等待事件 TopN", "SELECT EVENT, WAIT_CLASS, TOTAL_WAITS, TIME_WAITED FROM V$SYSTEM_EVENT WHERE WAIT_CLASS IS NOT NULL ORDER BY TIME_WAITED DESC LIMIT 30", 30),
            _db_step("long_sql", "长时间 SQL", "SELECT SQL_TEXT, EXEC_TIME, SESS_ID, N_RUNS, FINISH_TIME FROM V$LONG_EXEC_SQLS ORDER BY EXEC_TIME DESC LIMIT 50", 45),
        ],
    },
    {
        "id": "builtin-jdbc-database-core-readonly",
        "name": "JDBC 数据库核心只读巡检",
        "asset_type": "jdbc_database",
        "asset_types": ["xugu"],
        "protocol": "*",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version_probe",
                "title": "连接与版本探测",
                "tool": "db_execute_query",
                "sql": "SELECT 1",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-db2-core-readonly",
        "name": "DB2 核心只读巡检",
        "asset_type": "db2",
        "asset_types": ["db2"],
        "protocol": "db2",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version_probe",
                "title": "连接与版本探测",
                "tool": "db_execute_query",
                "sql": "SELECT 1 FROM SYSIBM.SYSDUMMY1",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-clickhouse-core-readonly",
        "name": "ClickHouse 核心只读巡检",
        "asset_type": "clickhouse",
        "protocol": "clickhouse",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version_probe",
                "title": "连接与版本探测",
                "tool": "database_api_request",
                "method": "GET",
                "path": "/?query=SELECT%201",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-elasticsearch-core-readonly",
        "name": "ElasticSearch 核心只读巡检",
        "asset_type": "elasticsearch",
        "protocol": "elasticsearch",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "cluster_health",
                "title": "集群健康",
                "tool": "database_api_request",
                "method": "GET",
                "path": "/_cluster/health",
                "timeout": 20,
            },
            {
                "name": "indices",
                "title": "索引列表",
                "tool": "database_api_request",
                "method": "GET",
                "path": "/_cat/indices?format=json",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-nebula-graph-core-readonly",
        "name": "NebulaGraph 核心只读巡检",
        "asset_type": "nebula_graph",
        "asset_types": ["nebula_graph", "nebula_graph_cluster"],
        "protocol": "nebula_graph",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "service_root",
                "title": "服务探测",
                "tool": "database_api_request",
                "method": "GET",
                "path": "/",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-memcached-core-readonly",
        "name": "Memcached 核心只读巡检",
        "asset_type": "memcached",
        "protocol": "memcached",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "服务版本",
                "tool": "memcached_execute_command",
                "command": "version",
                "timeout": 10,
            },
            {
                "name": "stats",
                "title": "运行统计",
                "tool": "memcached_execute_command",
                "command": "stats",
                "timeout": 15,
            },
        ],
    },
    {
        "id": "builtin-network-cli-core-readonly",
        "name": "网络设备 SSH CLI 核心只读巡检",
        "asset_type": "network_cli",
        "asset_types": ["switch", "firewall", "vpn"],
        "protocol": "ssh",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "设备版本与运行时间",
                "tool": "network_cli_execute_command",
                "command": "display version",
                "timeout": 20,
            },
            {
                "name": "cpu",
                "title": "CPU 状态",
                "tool": "network_cli_execute_command",
                "command": "display cpu-usage",
                "timeout": 15,
            },
            {
                "name": "memory",
                "title": "内存状态",
                "tool": "network_cli_execute_command",
                "command": "display memory",
                "timeout": 15,
            },
            {
                "name": "interfaces",
                "title": "接口摘要",
                "tool": "network_cli_execute_command",
                "command": "display interface brief",
                "timeout": 20,
            },
            {
                "name": "interface_errors",
                "title": "接口错误包",
                "tool": "network_cli_execute_command",
                "command": "display interface | include CRC|error|discard",
                "timeout": 30,
            },
            {
                "name": "neighbors",
                "title": "LLDP 邻居",
                "tool": "network_cli_execute_command",
                "command": "display lldp neighbor brief",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-snmp-core-readonly",
        "name": "SNMP 核心只读巡检",
        "asset_type": "*",
        "protocol": "snmp",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "system_description",
                "title": "系统描述",
                "tool": "snmp_get",
                "oid": "1.3.6.1.2.1.1.1.0",
                "timeout": 15,
            },
            {
                "name": "system_uptime",
                "title": "系统运行时间",
                "tool": "snmp_get",
                "oid": "1.3.6.1.2.1.1.3.0",
                "timeout": 15,
            },
            {
                "name": "interface_count",
                "title": "接口数量",
                "tool": "snmp_get",
                "oid": "1.3.6.1.2.1.2.1.0",
                "timeout": 15,
            },
            {
                "name": "system_name",
                "title": "系统名称",
                "tool": "snmp_get",
                "oid": "1.3.6.1.2.1.1.5.0",
                "timeout": 15,
            },
        ],
    },
    {
        "id": "builtin-vmware-core-readonly",
        "name": "VMware 核心只读巡检",
        "asset_type": "vmware",
        "protocol": "vmware",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "vCenter 版本",
                "tool": "virtualization_api_request",
                "operation": "version",
                "method": "GET",
                "path": "/api/appliance/system/version",
                "timeout": 20,
            },
            {
                "name": "hosts",
                "title": "主机列表",
                "tool": "virtualization_api_request",
                "operation": "hosts",
                "method": "GET",
                "path": "/api/vcenter/host",
                "timeout": 30,
            },
            {
                "name": "vms",
                "title": "虚拟机列表",
                "tool": "virtualization_api_request",
                "operation": "vms",
                "method": "GET",
                "path": "/api/vcenter/vm",
                "timeout": 30,
            },
            {
                "name": "datastores",
                "title": "数据存储",
                "tool": "virtualization_api_request",
                "operation": "datastores",
                "method": "GET",
                "path": "/api/vcenter/datastore",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-proxmox-core-readonly",
        "name": "Proxmox VE 核心只读巡检",
        "asset_type": "proxmox",
        "protocol": "proxmox",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "Proxmox 版本",
                "tool": "virtualization_api_request",
                "operation": "version",
                "method": "GET",
                "path": "/api2/json/version",
                "timeout": 20,
            },
            {
                "name": "nodes",
                "title": "节点列表",
                "tool": "virtualization_api_request",
                "operation": "nodes",
                "method": "GET",
                "path": "/api2/json/nodes",
                "timeout": 30,
            },
            {
                "name": "resources",
                "title": "集群资源",
                "tool": "virtualization_api_request",
                "operation": "resources",
                "method": "GET",
                "path": "/api2/json/cluster/resources",
                "timeout": 30,
            },
            {
                "name": "storage",
                "title": "存储列表",
                "tool": "virtualization_api_request",
                "operation": "storage",
                "method": "GET",
                "path": "/api2/json/storage",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-openstack-core-readonly",
        "name": "OpenStack 核心只读巡检",
        "asset_type": "openstack",
        "protocol": "openstack",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "version",
                "title": "Keystone 版本",
                "tool": "virtualization_api_request",
                "operation": "version",
                "method": "GET",
                "path": "/v3",
                "timeout": 20,
            },
            {
                "name": "catalog",
                "title": "服务目录",
                "tool": "virtualization_api_request",
                "operation": "catalog",
                "method": "GET",
                "path": "/v3/auth/catalog",
                "timeout": 30,
            },
            {
                "name": "servers",
                "title": "云主机列表",
                "tool": "virtualization_api_request",
                "operation": "servers",
                "method": "GET",
                "path": "compute:/servers/detail",
                "timeout": 30,
            },
            {
                "name": "hypervisors",
                "title": "计算节点",
                "tool": "virtualization_api_request",
                "operation": "hypervisors",
                "method": "GET",
                "path": "compute:/os-hypervisors/detail",
                "timeout": 30,
            },
            {
                "name": "networks",
                "title": "网络列表",
                "tool": "virtualization_api_request",
                "operation": "networks",
                "method": "GET",
                "path": "network:/networks",
                "timeout": 30,
            },
            {
                "name": "volumes",
                "title": "云硬盘列表",
                "tool": "virtualization_api_request",
                "operation": "volumes",
                "method": "GET",
                "path": "volume:/volumes/detail",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-zstack-core-readonly",
        "name": "ZStack 核心只读巡检",
        "asset_type": "zstack",
        "protocol": "zstack",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "management_nodes",
                "title": "管理节点",
                "tool": "virtualization_api_request",
                "operation": "management_nodes",
                "method": "GET",
                "path": "/zstack/v1/management-nodes",
                "timeout": 20,
            },
            {
                "name": "zones",
                "title": "区域列表",
                "tool": "virtualization_api_request",
                "operation": "zones",
                "method": "GET",
                "path": "/zstack/v1/zones",
                "timeout": 30,
            },
            {
                "name": "clusters",
                "title": "集群列表",
                "tool": "virtualization_api_request",
                "operation": "clusters",
                "method": "GET",
                "path": "/zstack/v1/clusters",
                "timeout": 30,
            },
            {
                "name": "hosts",
                "title": "物理机列表",
                "tool": "virtualization_api_request",
                "operation": "hosts",
                "method": "GET",
                "path": "/zstack/v1/hosts",
                "timeout": 30,
            },
            {
                "name": "vms",
                "title": "云主机列表",
                "tool": "virtualization_api_request",
                "operation": "vms",
                "method": "GET",
                "path": "/zstack/v1/vm-instances",
                "timeout": 30,
            },
            {
                "name": "volumes",
                "title": "云盘列表",
                "tool": "virtualization_api_request",
                "operation": "volumes",
                "method": "GET",
                "path": "/zstack/v1/volumes",
                "timeout": 30,
            },
            {
                "name": "l3_networks",
                "title": "三层网络",
                "tool": "virtualization_api_request",
                "operation": "l3_networks",
                "method": "GET",
                "path": "/zstack/v1/l3-networks",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-kvm-core-readonly",
        "name": "KVM/Libvirt 核心只读巡检",
        "asset_type": "kvm",
        "protocol": "ssh",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "nodeinfo",
                "title": "宿主机虚拟化信息",
                "tool": "linux_execute_command",
                "command": "virsh nodeinfo",
                "timeout": 20,
            },
            {
                "name": "vms",
                "title": "虚拟机列表",
                "tool": "linux_execute_command",
                "command": "virsh list --all",
                "timeout": 20,
            },
            {
                "name": "storage_pools",
                "title": "存储池",
                "tool": "linux_execute_command",
                "command": "virsh pool-list --all",
                "timeout": 20,
            },
            {
                "name": "networks",
                "title": "虚拟网络",
                "tool": "linux_execute_command",
                "command": "virsh net-list --all",
                "timeout": 20,
            },
            {
                "name": "disk",
                "title": "宿主机磁盘",
                "tool": "linux_execute_command",
                "command": "df -hP",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-object-storage-core-readonly",
        "name": "对象存储核心只读巡检",
        "asset_type": "object_storage",
        "asset_types": ["s3", "minio"],
        "protocol": "*",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "buckets",
                "title": "Bucket 列表",
                "tool": "storage_api_request",
                "operation": "list_buckets",
                "timeout": 20,
            },
            {
                "name": "default_bucket",
                "title": "默认 Bucket 可访问性",
                "tool": "storage_api_request",
                "operation": "head_bucket",
                "timeout": 20,
            },
            {
                "name": "bucket_location",
                "title": "默认 Bucket 区域",
                "tool": "storage_api_request",
                "operation": "get_bucket_location",
                "timeout": 20,
            },
            {
                "name": "objects",
                "title": "默认 Bucket 对象 TopN",
                "tool": "storage_api_request",
                "operation": "list_objects",
                "max_keys": 50,
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-backup-storage-core-readonly",
        "name": "备份/存储平台核心只读巡检",
        "asset_type": "backup",
        "protocol": "backup",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "health",
                "title": "平台健康状态",
                "tool": "storage_api_request",
                "operation": "health",
                "timeout": 20,
            },
            {
                "name": "jobs",
                "title": "备份任务",
                "tool": "storage_api_request",
                "operation": "jobs",
                "timeout": 30,
            },
            {
                "name": "repositories",
                "title": "仓库/介质",
                "tool": "storage_api_request",
                "operation": "repositories",
                "timeout": 30,
            },
            {
                "name": "policies",
                "title": "备份策略",
                "tool": "storage_api_request",
                "operation": "policies",
                "timeout": 30,
            },
            {
                "name": "capacity",
                "title": "容量概览",
                "tool": "storage_api_request",
                "operation": "capacity",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-ceph-core-readonly",
        "name": "Ceph 核心只读巡检",
        "asset_type": "ceph",
        "protocol": "ssh",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "status",
                "title": "集群状态",
                "tool": "storage_execute_command",
                "command": "ceph status",
                "timeout": 20,
            },
            {
                "name": "health",
                "title": "健康明细",
                "tool": "storage_execute_command",
                "command": "ceph health detail",
                "timeout": 30,
            },
            {
                "name": "osd_tree",
                "title": "OSD 拓扑",
                "tool": "storage_execute_command",
                "command": "ceph osd tree",
                "timeout": 30,
            },
            {
                "name": "osd_df",
                "title": "OSD 容量",
                "tool": "storage_execute_command",
                "command": "ceph osd df",
                "timeout": 30,
            },
            {
                "name": "df",
                "title": "存储池容量",
                "tool": "storage_execute_command",
                "command": "ceph df",
                "timeout": 30,
            },
            {
                "name": "mon",
                "title": "Monitor 状态",
                "tool": "storage_execute_command",
                "command": "ceph mon stat",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-nfs-core-readonly",
        "name": "NFS 核心只读巡检",
        "asset_type": "nfs",
        "protocol": "ssh",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "exports",
                "title": "导出目录",
                "tool": "storage_execute_command",
                "command": "exportfs -v",
                "timeout": 20,
            },
            {
                "name": "showmount",
                "title": "本机导出视图",
                "tool": "storage_execute_command",
                "command": "showmount -e localhost",
                "timeout": 20,
            },
            {
                "name": "service",
                "title": "服务状态",
                "tool": "storage_execute_command",
                "command": "systemctl is-active nfs-server || systemctl is-active nfs-kernel-server",
                "timeout": 15,
            },
            {
                "name": "ports",
                "title": "监听端口",
                "tool": "storage_execute_command",
                "command": "ss -lntup | grep -E ':(2049|111)\\b'",
                "timeout": 15,
            },
            {
                "name": "filesystem",
                "title": "文件系统容量",
                "tool": "storage_execute_command",
                "command": "df -hT",
                "timeout": 20,
            },
        ],
    },
    {
        "id": "builtin-hdfs-core-readonly",
        "name": "HDFS 核心只读巡检",
        "asset_type": "hdfs",
        "protocol": "ssh",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "report",
                "title": "集群报告",
                "tool": "storage_execute_command",
                "command": "hdfs dfsadmin -report",
                "timeout": 45,
            },
            {
                "name": "safemode",
                "title": "安全模式",
                "tool": "storage_execute_command",
                "command": "hdfs dfsadmin -safemode get",
                "timeout": 20,
            },
            {
                "name": "capacity",
                "title": "根目录容量",
                "tool": "storage_execute_command",
                "command": "hdfs dfs -df -h /",
                "timeout": 30,
            },
            {
                "name": "ha",
                "title": "HA 服务状态",
                "tool": "storage_execute_command",
                "command": "hdfs haadmin -getAllServiceState",
                "timeout": 30,
            },
        ],
    },
    {
        "id": "builtin-glusterfs-core-readonly",
        "name": "GlusterFS 核心只读巡检",
        "asset_type": "glusterfs",
        "protocol": "ssh",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "peers",
                "title": "Peer 状态",
                "tool": "storage_execute_command",
                "command": "gluster peer status",
                "timeout": 20,
            },
            {
                "name": "volumes",
                "title": "卷列表",
                "tool": "storage_execute_command",
                "command": "gluster volume list",
                "timeout": 20,
            },
            {
                "name": "volume_info",
                "title": "卷配置",
                "tool": "storage_execute_command",
                "command": "gluster volume info",
                "timeout": 30,
            },
            {
                "name": "volume_status",
                "title": "卷运行状态",
                "tool": "storage_execute_command",
                "command": "gluster volume status all",
                "timeout": 45,
            },
        ],
    },
    {
        "id": "builtin-redfish-core-readonly",
        "name": "Redfish 硬件核心只读巡检",
        "asset_type": "redfish",
        "protocol": "redfish",
        "enabled": True,
        "builtin": True,
        "readonly": True,
        "steps": [
            {
                "name": "service_root",
                "title": "Redfish Service Root",
                "tool": "http_api_request",
                "method": "GET",
                "path": "/redfish/v1/",
                "timeout": 20,
            },
            {
                "name": "systems",
                "title": "服务器系统",
                "tool": "http_api_request",
                "method": "GET",
                "path": "/redfish/v1/Systems",
                "timeout": 30,
            },
            {
                "name": "chassis",
                "title": "机箱硬件",
                "tool": "http_api_request",
                "method": "GET",
                "path": "/redfish/v1/Chassis",
                "timeout": 30,
            },
            {
                "name": "managers",
                "title": "带外管理器",
                "tool": "http_api_request",
                "method": "GET",
                "path": "/redfish/v1/Managers",
                "timeout": 30,
            },
        ],
    },
]
