export const TOOL_LABELS: Record<string, string> = {
  linux_execute_command: 'Linux/Unix 命令',
  winrm_execute_command: 'Windows PowerShell 命令',
  network_cli_execute_command: '网络设备 CLI',
  container_execute_command: '容器主机命令',
  middleware_execute_command: '中间件主机命令',
  storage_execute_command: '存储节点命令',
  db_execute_query: '数据库 SQL 执行',
  redis_execute_command: 'Redis 命令',
  memcached_execute_command: 'Memcached 命令',
  mongodb_find: 'MongoDB 查询',
  http_api_request: '通用 HTTP/API',
  database_api_request: '数据库管理接口',
  bigdata_api_request: '大数据平台接口',
  middleware_api_request: '中间件管理接口',
  discovery_api_request: '服务发现接口',
  container_api_request: '容器平台接口',
  network_api_request: '网络设备接口',
  security_api_request: '安全身份接口',
  cicd_api_request: 'CI/CD 平台接口',
  ai_platform_api_request: 'AI 平台接口',
  oob_api_request: '硬件带外接口',
  k8s_api_request: 'Kubernetes 集群 API',
  monitoring_api_query: '监控平台查询',
  virtualization_api_request: '虚拟化平台接口',
  storage_api_request: '存储/备份接口',
  service_probe_request: '业务服务探测',
  snmp_get: 'SNMP 读取',
}

export const STATUS_LABELS: Record<string, string> = {
  ready: '就绪',
  supported: '已支持',
  gap: '待补齐',
  success: '成功',
  error: '失败',
  failed: '失败',
  skipped: '跳过',
  completed: '完成',
  partial: '部分完成',
  empty: '无目标',
}

export const PROTOCOL_LABELS: Record<string, string> = {
  ssh: 'SSH',
  winrm: 'WinRM',
  telnet: 'Telnet',
  jdbc: 'JDBC',
  mysql: 'MySQL',
  oracle: 'Oracle',
  postgresql: 'PostgreSQL',
  mssql: 'SQL Server',
  db2: 'DB2',
  dameng: '达梦',
  xugu: '虚谷',
  hive: 'Hive JDBC',
  iotdb: 'IoTDB JDBC',
  clickhouse: 'ClickHouse',
  elasticsearch: 'ElasticSearch',
  nebula_graph: 'NebulaGraph',
  redis: 'Redis',
  memcached: 'Memcached',
  mongodb: 'MongoDB',
  http_api: '平台 API',
  http: 'HTTP/HTTPS',
  https: 'HTTPS',
  rest: 'REST API',
  tls: 'TLS/证书',
  websocket: 'WebSocket',
  tcp: 'TCP',
  udp: 'UDP',
  icmp: 'PING/ICMP',
  ftp: 'FTP',
  smtp: 'SMTP',
  pop3: 'POP3',
  imap: 'IMAP',
  mqtt: 'MQTT',
  ntp: 'NTP',
  modbus: 'Modbus',
  s7: 'S7',
  registry: '注册中心',
  dns: 'DNS',
  ipmi: 'IPMI',
  ldap: 'LDAP/AD',
  jmx: 'JMX',
  prometheus: 'Prometheus',
  kafka: 'Kafka',
  k8s: 'Kubernetes',
  kubernetes: 'Kubernetes',
  docker: 'Docker',
  vmware: 'VMware',
  openstack: 'OpenStack',
  proxmox: 'Proxmox',
  hyperv: 'Hyper-V',
  zstack: 'ZStack',
  s3: 'S3',
  minio: 'MinIO',
  backup: '备份平台',
  redfish: 'Redfish',
  snmp: 'SNMP',
  virtual: '虚拟会话',
}

export const ASSET_TYPE_LABELS: Record<string, string> = {
  linux: 'Linux 主机',
  unix: 'Unix 主机',
  aix: 'AIX 主机',
  windows: 'Windows 主机',
  mysql: 'MySQL 数据库',
  oracle: 'Oracle 数据库',
  postgresql: 'PostgreSQL 数据库',
  mssql: 'SQL Server 数据库',
  db2: 'DB2 数据库',
  dameng: '达梦数据库',
  xugu: '虚谷数据库',
  clickhouse: 'ClickHouse 数据库',
  elasticsearch: 'ElasticSearch',
  nebula_graph: 'NebulaGraph 图数据库',
  redis: 'Redis 缓存',
  memcached: 'Memcached 缓存',
  mongodb: 'MongoDB 文档库',
  doris_fe: 'Apache Doris FE',
  doris_be: 'Apache Doris BE',
  starrocks_fe: 'StarRocks FE',
  starrocks_be: 'StarRocks BE',
  greptime: 'GreptimeDB',
  hbase_master: 'HBase Master',
  hbase_regionserver: 'HBase RegionServer',
  hive: 'Apache Hive',
  hugegraph: 'HugeGraph',
  influxdb: 'InfluxDB',
  iotdb: 'Apache IoTDB',
  iceberg: 'Apache Iceberg',
  kafka_client: 'Kafka 客户端入口',
  jvm: 'JVM/JMX',
  shenyu: 'Apache ShenYu',
  spring_gateway: 'Spring Cloud Gateway',
  k8s: 'Kubernetes 集群',
  kubernetes: 'Kubernetes 集群',
  docker: 'Docker 主机',
  harbor: 'Harbor 镜像仓库',
  vmware: 'VMware 虚拟化',
  openstack: 'OpenStack 云平台',
  proxmox: 'Proxmox 虚拟化',
  hyperv: 'Hyper-V 虚拟化',
  zstack: 'ZStack 云平台',
  switch: '交换机',
  router: '路由器',
  firewall: '防火墙',
  f5: 'F5 负载均衡',
  a10: 'A10 负载均衡',
  waf: 'WAF',
  dns: 'DNS 服务',
  vpn: 'VPN 网关',
  s3: 'S3 对象存储',
  minio: 'MinIO 对象存储',
  ceph: 'Ceph 存储',
  nas: 'NAS 存储',
  san: 'SAN 存储',
  nfs: 'NFS 存储',
  hdfs: 'HDFS 存储',
  glusterfs: 'GlusterFS 存储',
  backup: '备份平台',
  prometheus: 'Prometheus',
  grafana: 'Grafana',
  zabbix: 'Zabbix',
  alertmanager: 'Alertmanager',
  loki: 'Loki',
  hertzbeat: 'HertzBeat',
  bastion: '堡垒机',
  ldap: 'LDAP/目录服务',
  audit: '审计平台',
  api: '业务 API',
  website: '网站服务',
  ssl_cert: 'SSL 证书',
  port: '端口服务',
  ping: '连通性探测',
}

export const TOOLSET_LABELS: Record<string, string> = {
  'linux-ssh': 'Linux 运维工具',
  'windows-winrm': 'Windows 运维工具',
  'network-cli': '网络 CLI 工具',
  'sql-db': '数据库 SQL 工具',
  redis: 'Redis 工具',
  memcached: 'Memcached 工具',
  mongodb: 'MongoDB 工具',
  'http-api': '通用 API 工具',
  'database-api': '数据库平台接口',
  'bigdata-api': '大数据平台接口',
  'middleware-api': '中间件管理接口',
  'discovery-api': '服务发现接口',
  'container-api': '容器平台接口',
  'network-api': '网络设备接口',
  'security-api': '安全身份接口',
  'cicd-api': 'CI/CD 平台接口',
  'ai-platform-api': 'AI 平台接口',
  'oob-api': '硬件带外接口',
  kubernetes: 'Kubernetes 工具',
  monitoring: '监控平台工具',
  virtualization: '虚拟化平台工具',
  storage: '存储/备份工具',
  'service-probe': '服务探测工具',
  snmp: 'SNMP 读取工具',
  'container-runtime': '容器运行时工具',
  'middleware-ssh': '中间件主机工具',
  'storage-ssh': '存储节点工具',
  'skill-runtime': '技能运行时',
  knowledge: '知识库',
  platform: '平台工具',
  interaction: '交互确认',
  orchestration: '编排调度',
  batch: '批量任务',
}

export const CATEGORY_LABELS: Record<string, string> = {
  os: '操作系统与主机',
  db: '数据库与缓存',
  database: '数据库与缓存',
  container: '容器与云原生',
  middleware: '中间件',
  bigdata: '大数据',
  monitor: '监控与告警',
  virtualization: '虚拟化与云平台',
  network: '网络与安全',
  storage: '存储与备份',
  oob: '带外管理',
  service: '业务服务',
  discovery: '服务发现',
  security: '安全与身份',
  ai: 'AI 算力平台',
  cicd: '研发与发布',
  custom: '自定义资产',
  other: '其他',
}
