import type { AssetCategoryOption, AssetSubType } from './connectionModalHelpers'

export const ASSET_CATEGORIES: AssetCategoryOption[] = [
  { id: 'os', label: '操作系统与主机', group: '基础设施' },
  { id: 'db', label: '数据库与缓存', group: '数据服务' },
  { id: 'container', label: '容器与云原生', group: '基础设施' },
  { id: 'middleware', label: '中间件与消息', group: '应用支撑' },
  { id: 'bigdata', label: '大数据与分析', group: '数据服务' },
  { id: 'network', label: '网络设备', group: '基础设施' },
  { id: 'storage', label: '存储与备份', group: '基础设施' },
  { id: 'virtualization', label: '虚拟化与私有云', group: '基础设施' },
  { id: 'monitor', label: '监控与告警', group: '平台工具' },
  { id: 'service', label: '应用与网络服务', group: '平台工具' },
  { id: 'discovery', label: '服务发现', group: '平台工具' },
  { id: 'oob', label: '硬件带外', group: '基础设施' },
  { id: 'security', label: '安全与身份', group: '平台工具' },
  { id: 'ai', label: 'AI 与大模型', group: '平台工具' },
  { id: 'cicd', label: 'CI/CD 与发布', group: '平台工具' },
  { id: 'custom', label: '自定义与扩展', group: '其它' },
  { id: 'other', label: '其它', group: '其它' },
]

export const CATEGORY_LABELS: Record<string, string> = Object.fromEntries(
  ASSET_CATEGORIES.map((item) => [item.id, item.label])
)

export const ASSET_SUB_TYPES: Record<string, AssetSubType[]> = {
  os: [
    { id: 'linux', label: 'Linux / Unix 主机 (SSH)', asset_type: 'ssh', defaultPort: 22 },
    { id: 'windows', label: 'Windows Server (WinRM)', asset_type: 'winrm', defaultPort: 5985 },
  ],
  db: [
    { id: 'mysql', label: 'MySQL', asset_type: 'mysql', defaultPort: 3306 },
    { id: 'oracle', label: 'Oracle', asset_type: 'oracle', defaultPort: 1521 },
    { id: 'postgresql', label: 'PostgreSQL', asset_type: 'postgresql', defaultPort: 5432 },
    { id: 'mssql', label: 'SQL Server', asset_type: 'mssql', defaultPort: 1433 },
    { id: 'redis', label: 'Redis', asset_type: 'redis', defaultPort: 6379, authMode: 'password_only' },
    { id: 'mongodb', label: 'MongoDB', asset_type: 'mongodb', defaultPort: 27017 },
    { id: 'clickhouse', label: 'ClickHouse', asset_type: 'clickhouse', defaultPort: 8123 },
    { id: 'elasticsearch', label: 'ElasticSearch', asset_type: 'elasticsearch', defaultPort: 9200 },
    { id: 'nebula_graph', label: 'NebulaGraph', asset_type: 'nebula_graph', defaultPort: 9669 },
  ],
  container: [
    { id: 'docker', label: 'Docker Host (SSH)', asset_type: 'ssh', defaultPort: 22 },
    { id: 'containerd', label: 'containerd Host (SSH)', asset_type: 'ssh', defaultPort: 22 },
    { id: 'podman', label: 'Podman Host (SSH)', asset_type: 'ssh', defaultPort: 22 },
    { id: 'harbor', label: 'Harbor 镜像仓库', asset_type: 'http_api', defaultPort: 443 },
    { id: 'k8s', label: 'Kubernetes (K8s)', asset_type: 'k8s', defaultPort: 6443 },
  ],
  middleware: [
    { id: 'nginx', label: 'Nginx', asset_type: 'ssh', defaultPort: 22 },
    { id: 'tomcat', label: 'Tomcat', asset_type: 'ssh', defaultPort: 22 },
    { id: 'kafka', label: 'Kafka', asset_type: 'ssh', defaultPort: 22 },
    { id: 'rabbitmq', label: 'RabbitMQ', asset_type: 'http_api', defaultPort: 15672 },
    { id: 'rocketmq', label: 'RocketMQ', asset_type: 'ssh', defaultPort: 22 },
    { id: 'zookeeper', label: 'ZooKeeper', asset_type: 'ssh', defaultPort: 22 },
    { id: 'nacos', label: 'Nacos', asset_type: 'http_api', defaultPort: 8848 },
    { id: 'consul', label: 'Consul', asset_type: 'http_api', defaultPort: 8500 },
  ],
  virtualization: [
    { id: 'vmware', label: 'VMware vCenter / ESXi', asset_type: 'vmware', defaultPort: 443 },
    { id: 'kvm', label: 'KVM / Libvirt 宿主机 (SSH)', asset_type: 'ssh', defaultPort: 22 },
    { id: 'openstack', label: 'OpenStack', asset_type: 'openstack', defaultPort: 5000 },
    { id: 'proxmox', label: 'Proxmox VE', asset_type: 'proxmox', defaultPort: 8006 },
    { id: 'hyperv', label: 'Hyper-V (WinRM)', asset_type: 'winrm', defaultPort: 5985 },
    { id: 'zstack', label: 'ZStack', asset_type: 'zstack', defaultPort: 8080 },
  ],
  network: [
    { id: 'f5', label: 'F5 BIG-IP 负载均衡', asset_type: 'http_api', defaultPort: 443 },
    { id: 'switch', label: '交换机 / 路由器', asset_type: 'ssh', defaultPort: 22 },
    { id: 'firewall', label: '防火墙', asset_type: 'ssh', defaultPort: 22 },
    { id: 'a10', label: 'A10 负载均衡', asset_type: 'http_api', defaultPort: 443 },
    { id: 'waf', label: 'WAF', asset_type: 'http_api', defaultPort: 443 },
    { id: 'vpn', label: 'VPN 网关', asset_type: 'ssh', defaultPort: 22 },
  ],
  storage: [
    { id: 'ceph', label: 'Ceph 集群', asset_type: 'ssh', defaultPort: 22 },
    { id: 'nfs', label: 'NFS 服务', asset_type: 'ssh', defaultPort: 22 },
    { id: 'nas', label: 'NAS / SAN (SNMP)', asset_type: 'snmp', defaultPort: 161, authMode: 'custom_snmp' },
    { id: 'minio', label: 'MinIO', asset_type: 'minio', defaultPort: 9000 },
    { id: 's3', label: 'S3 / 对象存储', asset_type: 's3', defaultPort: 443 },
    { id: 'hdfs', label: 'HDFS', asset_type: 'ssh', defaultPort: 22 },
    { id: 'glusterfs', label: 'GlusterFS', asset_type: 'ssh', defaultPort: 22 },
    { id: 'backup', label: '备份系统', asset_type: 'backup', defaultPort: 443 },
  ],
  monitor: [
    { id: 'zabbix', label: 'Zabbix', asset_type: 'http_api', defaultPort: 80 },
    { id: 'prometheus', label: 'Prometheus', asset_type: 'http_api', defaultPort: 9090 },
    { id: 'alertmanager', label: 'Alertmanager', asset_type: 'http_api', defaultPort: 9093 },
    { id: 'grafana', label: 'Grafana', asset_type: 'http_api', defaultPort: 3000 },
    { id: 'loki', label: 'Loki', asset_type: 'http_api', defaultPort: 3100 },
    { id: 'victoriametrics', label: 'VictoriaMetrics', asset_type: 'http_api', defaultPort: 8428 },
    { id: 'manageengine', label: '卓豪 ManageEngine', asset_type: 'http_api', defaultPort: 8443 },
  ],
  oob: [
    { id: 'snmp', label: 'SNMP', asset_type: 'snmp', defaultPort: 161, authMode: 'custom_snmp' },
    { id: 'redfish', label: 'Redfish / iLO / iDRAC', asset_type: 'redfish', defaultPort: 443 },
    { id: 'ipmi', label: 'IPMI', asset_type: 'ipmi', defaultPort: 623 },
  ],
  security: [
    { id: 'bastion', label: '堡垒机 / Bastion', asset_type: 'http_api', defaultPort: 443 },
    { id: 'ldap', label: 'LDAP / Active Directory', asset_type: 'ldap', defaultPort: 389 },
    { id: 'audit', label: '审计平台', asset_type: 'http_api', defaultPort: 443 },
  ],
  service: [
    { id: 'website', label: '网站监测', asset_type: 'http', defaultPort: 80 },
    { id: 'ssl_cert', label: 'SSL 证书', asset_type: 'tls', defaultPort: 443 },
    { id: 'dns', label: 'DNS 服务', asset_type: 'dns', defaultPort: 53, authMode: 'none' },
    { id: 'port', label: 'TCP 端口', asset_type: 'tcp', defaultPort: 80 },
    { id: 'udp_port', label: 'UDP 端口', asset_type: 'udp', defaultPort: 53 },
    { id: 'ping', label: 'PING 连通性', asset_type: 'icmp', defaultPort: 0, authMode: 'none' },
    { id: 'ftp', label: 'FTP 服务', asset_type: 'ftp', defaultPort: 21 },
    { id: 'smtp', label: 'SMTP 邮件服务', asset_type: 'smtp', defaultPort: 25 },
    { id: 'pop3', label: 'POP3 邮件服务', asset_type: 'pop3', defaultPort: 110 },
    { id: 'netease_mailbox', label: '网易邮箱', asset_type: 'imap', defaultPort: 993 },
    { id: 'qq_mailbox', label: 'QQ 邮箱', asset_type: 'imap', defaultPort: 993 },
    { id: 'mqtt', label: 'MQTT 连接', asset_type: 'mqtt', defaultPort: 1883 },
    { id: 'ntp', label: 'NTP 服务', asset_type: 'ntp', defaultPort: 123, authMode: 'none' },
    { id: 'modbus', label: 'Modbus 服务', asset_type: 'modbus', defaultPort: 502 },
    { id: 's7', label: 'S7 服务', asset_type: 's7', defaultPort: 102 },
    { id: 'registry', label: '注册中心监控', asset_type: 'registry', defaultPort: 80 },
    { id: 'websocket', label: 'WebSocket', asset_type: 'websocket', defaultPort: 80 },
  ],
}
