import type { DomainDefinition } from './safetyPolicyShared'

export const SAFETY_POLICY_DOMAINS: DomainDefinition[] = [
  {
    id: 'os',
    label: '主机系统',
    icon: '主',
    category: 'linux',
    platforms: ['Linux', 'Windows', 'KVM Host'],
    objects: '服务、文件、进程、账号、系统配置',
    hint: '巡检和查询默认允许，重启、改配置、删文件进入审批，格式化和破坏性命令禁止执行。',
    examples: [
      { action: '查看系统状态', decision: 'allow', example: 'uptime / df -h / systemctl status' },
      { action: '重启服务', decision: 'approval', example: 'systemctl restart nginx' },
      { action: '格式化磁盘', decision: 'deny', example: 'mkfs.ext4 /dev/sda' },
    ],
  },
  {
    id: 'database',
    label: '数据库',
    icon: '数',
    category: 'sql',
    platforms: ['MySQL', 'PostgreSQL', 'Oracle', 'SQL Server', 'MongoDB', 'Redis', 'Memcached', 'ElasticSearch'],
    objects: '库、表、索引、缓存 Key、集合',
    hint: '结构查询和状态查询允许，写入和结构变更需要审批，删库清库类动作禁止执行。',
    examples: [
      { action: '查询表结构', decision: 'allow', example: 'show create table orders' },
      { action: '修改数据', decision: 'approval', example: 'update orders set status = ...' },
      { action: '清空数据库', decision: 'deny', example: 'drop database prod' },
    ],
  },
  {
    id: 'cloudnative',
    label: '容器与云原生',
    icon: '容',
    category: 'http',
    platforms: ['Kubernetes', 'Docker', 'containerd', 'Harbor'],
    objects: 'Pod、Deployment、Namespace、镜像、Secret',
    hint: '查看资源和事件允许，扩缩容与重启需要审批，删除命名空间和敏感对象禁止执行。',
    examples: [
      { action: '查看 Pod', decision: 'allow', example: 'GET /api/v1/pods' },
      { action: '扩缩容 Deployment', decision: 'approval', example: 'PATCH /apis/apps/v1/deployments' },
      { action: '删除 Namespace', decision: 'deny', example: 'DELETE /api/v1/namespaces/prod' },
    ],
  },
  {
    id: 'virtualization',
    label: '虚拟化与私有云',
    icon: '虚',
    category: 'http',
    platforms: ['VMware', 'Proxmox', 'OpenStack', 'ZStack', 'Hyper-V'],
    objects: '虚拟机、宿主机、资源池、快照、卷',
    hint: '查询容量和虚拟机状态允许，重启、迁移、快照回滚需要审批，删除虚拟机和卷禁止执行。',
    examples: [
      { action: '查看虚拟机状态', decision: 'allow', example: 'GET /vms' },
      { action: '重启虚拟机', decision: 'approval', example: 'POST /vms/{id}/reboot' },
      { action: '删除虚拟机', decision: 'deny', example: 'DELETE /vms/{id}' },
    ],
  },
  {
    id: 'network',
    label: '网络与安全设备',
    icon: '网',
    category: 'network',
    platforms: ['Switch', 'Router', 'Firewall', 'F5', 'A10', 'WAF', 'VPN'],
    objects: '接口、路由、ACL、NAT、负载均衡策略',
    hint: 'show/display/ping 允许，进入配置模式和保存配置需要审批，清空配置禁止执行。',
    examples: [
      { action: '查看接口状态', decision: 'allow', example: 'display interface brief' },
      { action: '下发配置', decision: 'approval', example: 'system-view / configure terminal' },
      { action: '清空配置', decision: 'deny', example: 'reset saved-configuration' },
    ],
  },
  {
    id: 'middleware',
    label: '中间件与消息队列',
    icon: '中',
    category: 'http',
    platforms: ['Nginx', 'Apache', 'Tomcat', 'WebLogic', 'WebSphere', 'Kafka', 'RabbitMQ', 'RocketMQ', 'Nacos', 'Consul', 'Etcd'],
    objects: '实例、配置、Topic、Consumer、注册服务、路由规则',
    hint: '状态查询和配置查看允许，重载配置、发布配置、删除 Topic/服务需要审批或禁止执行。',
    examples: [
      { action: '查看运行状态', decision: 'allow', example: 'GET /actuator/health' },
      { action: '重载配置', decision: 'approval', example: 'nginx -s reload / POST /config/publish' },
      { action: '删除 Topic', decision: 'deny', example: 'DELETE /topics/payments' },
    ],
  },
  {
    id: 'bigdata',
    label: '大数据平台',
    icon: '大',
    category: 'http',
    platforms: ['Hadoop', 'HDFS', 'YARN', 'Hive', 'Spark', 'Flink', 'HBase', 'Doris', 'StarRocks'],
    objects: '任务、队列、表、分区、NameNode、作业集群',
    hint: '元数据和任务状态查询允许，停止任务、删除表分区、调整队列资源需要审批。',
    examples: [
      { action: '查看任务状态', decision: 'allow', example: 'GET /ws/v1/cluster/apps' },
      { action: '停止作业', decision: 'approval', example: 'PUT /jobs/{id}/yarn-cancel' },
      { action: '删除表分区', decision: 'deny', example: 'ALTER TABLE fact DROP PARTITION' },
    ],
  },
  {
    id: 'storage',
    label: '存储与备份 / S3',
    icon: '存',
    category: 'http',
    platforms: ['S3', 'MinIO', 'Ceph RGW', 'OSS', 'COS', 'OBS', 'Ceph', 'NAS/SAN', '备份平台'],
    objects: 'Bucket、Object、Policy、生命周期、存储池、备份任务',
    hint: '列目录和查元数据允许，下载对象默认审批，删除 Bucket、公开 Bucket、清空 Bucket 禁止执行。',
    examples: [
      { action: '查看 Bucket 列表', decision: 'allow', example: 'GET /?list-type=2' },
      { action: '下载对象', decision: 'approval', example: 'GET /bucket/object.zip' },
      { action: '删除 Bucket', decision: 'deny', example: 'DELETE /bucket' },
    ],
  },
  {
    id: 'cicd',
    label: 'CI/CD 与制品库',
    icon: '发',
    category: 'http',
    platforms: ['Jenkins', 'GitLab', 'Argo CD', 'Nexus', 'SonarQube', 'Artifactory'],
    objects: '流水线、发布任务、制品、镜像、代码仓库、质量门禁',
    hint: '查看构建和制品信息允许，触发发布、回滚部署、删除制品需要审批。',
    examples: [
      { action: '查看流水线状态', decision: 'allow', example: 'GET /jobs/prod-build/lastBuild' },
      { action: '触发生产发布', decision: 'approval', example: 'POST /job/prod-deploy/build' },
      { action: '删除制品', decision: 'deny', example: 'DELETE /repository/releases/app.jar' },
    ],
  },
  {
    id: 'ai',
    label: 'AI 算力平台',
    icon: '算',
    category: 'http',
    platforms: ['NVIDIA GPU', 'Ray', 'MLflow', 'Kubeflow', 'Volcano', 'Slurm'],
    objects: 'GPU、训练任务、模型、实验、队列、算力配额',
    hint: '查看资源和任务允许，停止训练、释放 GPU、删除模型需要审批或禁止执行。',
    examples: [
      { action: '查看 GPU 使用率', decision: 'allow', example: 'GET /metrics/gpu' },
      { action: '停止训练任务', decision: 'approval', example: 'POST /jobs/{id}/stop' },
      { action: '删除模型版本', decision: 'deny', example: 'DELETE /models/prod/v12' },
    ],
  },
  {
    id: 'monitoring',
    label: '监控与告警',
    icon: '告',
    category: 'http',
    platforms: ['Prometheus', 'Alertmanager', 'Grafana', 'Loki', 'Zabbix', 'ManageEngine'],
    objects: '指标、日志、告警、静默、规则、Dashboard',
    hint: '查询指标和日志允许，静默告警和改规则需要审批，删除规则可配置为禁止执行。',
    examples: [
      { action: '查询指标', decision: 'allow', example: 'GET /api/v1/query?query=up' },
      { action: '创建告警静默', decision: 'approval', example: 'POST /api/v2/silences' },
      { action: '删除告警规则', decision: 'deny', example: 'DELETE /api/ruler/rules' },
    ],
  },
  {
    id: 'hardware',
    label: '硬件带外管理',
    icon: '硬',
    category: 'http',
    platforms: ['SNMP', 'Redfish', 'iLO', 'iDRAC', 'IPMI'],
    objects: '传感器、电源、启动项、BIOS、硬件事件',
    hint: '读取硬件状态允许，修改启动项和远程电源操作需要审批或禁止执行。',
    examples: [
      { action: '读取传感器', decision: 'allow', example: 'GET /redfish/v1/Chassis' },
      { action: '远程重启', decision: 'approval', example: 'POST /Actions/ComputerSystem.Reset' },
      { action: '修改启动项', decision: 'deny', example: 'PATCH /Boot' },
    ],
  },
  {
    id: 'platform',
    label: '平台自身能力',
    icon: '平',
    category: 'local',
    platforms: ['本地脚本', '技能变更', '知识库', '自动化任务'],
    objects: '脚本、技能文件、策略、任务、平台文件',
    hint: '平台自修改能力风险最高，本地脚本和技能变更应默认审批，删除平台文件禁止执行。',
    examples: [
      { action: '读取平台状态', decision: 'allow', example: 'list_active_sessions' },
      { action: '执行本地脚本', decision: 'approval', example: 'local_execute_script' },
      { action: '删除平台文件', decision: 'deny', example: 'rm -rf ./data' },
    ],
  },
]
